# Generated by Django 4.2.17 on 2025-01-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='questions_avatars/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
