# Generated by Django 4.2.17 on 2025-01-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_question_avatar_alter_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.jpeg', null=True, upload_to='avatars/'),
        ),
    ]
